name: weather_api_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  http: ^1.3.0
  get_it: ^8.0.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
